jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /Users/manasiadawatkar/Documents/DBT/dbt-tutorial-360301-35e2f8a7ff7f.json
      project: dbt-tutorial-360301
      dataset: dbt_madawatkar
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
