jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /secrets/dbt-service-keyfile
      project: dbt-project-365823
      dataset: dbt_madawatkar
      threads: 4
      timeout_seconds: 300
      location: us-central1
      priority: interactive
